version: '3'
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=mdi-prod
        - REACT_APP_TITLE=mdi-title
    ports:
      - "80:80"